"""add created_date, created_time, refresh_token to users

Revision ID: d5977017b565
Revises: da97be7f3087
Create Date: 2025-03-19 19:12:55.057209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5977017b565'
down_revision: Union[str, None] = 'da97be7f3087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('created_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_time')
    op.drop_column('users', 'created_date')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
